<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="Waher.Content" Version="3.6.3" />
    <PackageReference Include="Waher.Content.Images" Version="3.2.0" />
    <PackageReference Include="Waher.Networking" Version="4.6.8" />
  </ItemGroup>

</Project>
